// Avatar piece descriptive names mapping
// This file maps avatar piece IDs to descriptive names for AI image generation

export const avatarDescriptions: Record<string, string> = {
  // Male heads - using actual IDs from avatar system
  'male-head-3': 'short black hair, bangs just above the eyebrows, glasses',
  'male-head-4': 'black russian style hat, with black ski glasses with transparent lenses',
  'male-head-5': 'green cap, opaque glasses and green alien skin',
  'male-head-6': 'beige hat with horns, opaque glasses and dark green skin',
  'male-head-7': 'bright purple fedora, short blue hair under it, opaque glasses and yellow skin',
  'male-head-8': 'light blue magician hat with a orange stripe at the base, dark blue skin',
  'male-head-9': 'bright green cap, ski glasses with opaque lenses and dark grey skin',
  'male-head-10': 'greenish fedora with a purplish stripe at the base, round opaque glasses and dark green skin',
  'male-head-11': 'green squared hat, purple long hair, glasses with transparent lenses and dark yellow skin',
  'male-head-12': 'blueberry colored beanie, light blue medium length hair, opaque glasses and pale greenish skin',
  'male-head-13': 'yellow magician hat with dark green stripe at the bottom, opaque glasses and light blue skin',
  'male-head-14': 'green beanie with small horns, monocle on right eye, opaque monocle on left eye, purple skin',
  'male-head-15': 'pink brimless cap, short light purple hair, darkish skin with one-piece glasses',
  'male-head-16': 'pink headband, short brown hair, glasses, pointy ears',
  'male-head-17': 'light green beanie, glasses, light blue skin',
  'male-head-18': 'light beige magician hat with brown stripe at the base, blue skin, green eyes',
  'male-head-19': 'pink beanie, opaque glasses, pointy ears',
  'male-head-20': 'light grey magician hat with purple stripe at the base, one-piece glasses, jet black #000000 HEX skin, red muttonchops',
  
  // Female heads - using actual IDs from avatar system
  'female-head-avatar': 'short black hair, parted in the middle, caucasian skin',
  'female-head-2': 'short black hair, bangs above the eyebrows, pointy ears, caucasian skin',
  'female-head-3': 'short black hair, bangs above the eyebrows, green eyes, caucasian skin',
  'female-head-4': 'long black hair with a middle part, pointy ears, caucasian skin',
  'female-head-5': 'black beanie, monocle on left eye, pointy ears, caucasian skin',
  'female-head-6': 'teal cap, teal long hair, glasses, dark skin',
  'female-head-7': 'green beanie, purple skin, glasses',
  'female-head-8': 'blue and yellow beanie, green long hair, monocle on right eye, brown skin',
  'female-head-9': 'bright green magician hat with purple stripe at the base, blond curtains hair, monocle on left eye, pale skin',
  'female-head-10': 'pink and green cap, dark pink hair, red skin',
  'female-head-11': 'white and beige cap, purple long hair, purple skin, one-piece glasses',
  'female-head-12': 'purple brimless cap, pale green skin, red cornrows hair, pointy ears, glasses',
  'female-head-13': 'blue fedora with bright green stripe at base, red hair with boxed bangs, cyan skin, opaque monocle on right eye',
  'female-head-14': 'dark blue squared hat with red stripe at the base, long blue hair, yellow skin, glasses',
  'female-head-15': 'golden-greenish beanie, cyan skin, opaque monocle on right eye',
  'female-head-16': 'orange hat with light blue stripe at the base, grey skin, bright green medium length curly hair, bright green eyes, glasses',
  'female-head-17': 'light brown to blonde hair, one-piece glasses, pale skin',
  'female-head-18': 'bright green brimless cap, green skin, green long hair, squinting eyes',
  'female-head-19': 'pale green beanie with pale pink base, purple skin, opaque glasses',
  'female-head-20': 'dark cyan medium length hair with a side bang, opaque glasses, teal skin',
  
  // Male torsos - using actual IDs from avatar system
  'male-torso-3': 'black open jacket with light blue and white t-shirt under',
  'male-torso-4': 'black open long jacket with light blue t-shirt under',
  'male-torso-5': 'red jacket with green and purple t-shirt under',
  'male-torso-6': '3 colors sweater, aquatic blue at the top, pale red in the middle, pale green at the bottom',
  'male-torso-7': 'horizontal striped vest wih bright green and pale blue stripes, plain green undershirt',
  'male-torso-8': 'bright pink jacket, brown scarf, blue and pink t-shirt under',
  'male-torso-9': 'horizontal striped vest with light blue and light purple stripes, dark yellow undershirt',
  'male-torso-10': 'horizontal striped vest with beige and brown stripes, bright green undershirt',
  'male-torso-11': 'pale gold shirt with teal undershirt',
  'male-torso-12': 'bright yellow vest with pale green undershirt',
  'male-torso-13': 'horizontal striped vest with pink and light blue stripes, pink undershirt',
  'male-torso-14': 'green open dress shirt, green undershirt, red and brown scarf',
  'male-torso-15': 'grey dress shirt, half green half purple undershirt, cyan scarf',
  'male-torso-16': '3 colors vest, pink at the top, yellow in the middle, pale orange at the bottom, bright green undershirt',
  'male-torso-17': 'brown vest with green and purple undershirt',
  'male-torso-18': 'green open dress shirt, pink to purple undershirt',
  'male-torso-19': 'beige open dress shirt with pale purple undershirt, cyan/dark purple/pale green 3 colored scarf',
  'male-torso-20': 'dark red vest with aquatic green undershirt and dark blue bow tie',
  
  // Female torsos - using actual IDs from avatar system
  'female-torso-2': 'bright green sleeveless shirt with yellow circle on chest',
  'female-torso-3': 'bright orange sleeveless shirtwith red sides and pink buttons',
  'female-torso-4': 'bright blue regular t-shirt',
  'female-torso-5': 'black jacket with bright blue undershirt',
  'female-torso-6': 'pale aqua colored undershirt with red top and brown bottom cropped open dress shirt and pink necklace',
  'female-torso-7': 'pink jacket, yellow undershirt, half green sleeves',
  'female-torso-8': 'horizontal striped vest with dark yellow and blue stripes, purple undershirt, bright green bow tie',
  'female-torso-9': 'bright green jacket with yellow sleeves',
  'female-torso-10': 'yellowish beige open dress shirt, green undershirt, grey bow tie',
  'female-torso-11': 'horizontal striped jacket with bright purple and grey stripes, purple sleeves, purple undershirt',
  'female-torso-12': 'dark blue jacket with pink undershirt',
  'female-torso-13': 'light purple open dress shirt with pale beige stripe at the bottom, blue undershirt, red belt',
  'female-torso-14': 'light purple shirt with dark pink horizontal stripe at the bottom, big gold bow tie',
  'female-torso-15': 'dark grey vest with striped green and light grey undershirt, green sleeves',
  'female-torso-16': 'half light blue and half purple sweater with green sleeves and big black bow tie',
  'female-torso-17': 'dark gold jacket with bright green undershirt and light pink bowtie',
  'female-torso-18': 'purple jacket with green sleeves and pale blue undershirt',
  'female-torso-19': 'grey open dress shirt with half blue half green undershirt, yellow shoulder pads and purple bow tie',
  'female-torso-20': 'bright green dress shirt with green undershirt and dark red small bow tie',
  'female-torso-avatar': 'simple purple sleeveless shirt',
  
  // Male legs - using actual IDs from avatar system
  'male-legs-3': 'black pants with black boots',
  'male-legs-4': 'light blue jeans, beige right sneaker, black left sneaker',
  'male-legs-5': 'pale purple large pants with pink slides',
  'male-legs-6': 'pale green pants with red sneakers',
  'male-legs-7': 'half purple half blue pants, red right sneaker, teal left sneaker',
  'male-legs-8': 'pink shorts with grey tall boots',
  'male-legs-9': 'green shorts, right green tall boot, left orange tall boot',
  'male-legs-10': 'dark blue pants with green vertical stripes on the side, green sneakers',
  'male-legs-11': 'brown shorts with tall magenta socks and magenta sneakers',
  'male-legs-12': 'bright green shorts with bright blue long underpants and brown sneakers',
  'male-legs-13': 'pale purple shorts with red long underpants and white sneakers',
  'male-legs-14': 'brownish orange pants with purple low sneakers',
  'male-legs-15': 'dark blue jeans with emerald sneakers',
  'male-legs-16': '2 colors pants, right leg grey, left leg bright blue, purple high sneakers',
  'male-legs-17': 'atomic green baggy pants with purple sneakers',
  'male-legs-18': 'dark green shorts with purple high sneakers',
  'male-legs-19': 'gold shorts with red sneakers',
  'male-legs-20': 'cyan shorts with green sneakers with magenta soles',
  
  // Female legs - using actual IDs from avatar system
  'female-legs-2': 'short grey skirt with tall black boots',
  'female-legs-3': 'pale blue pants with high black sneakers',
  'female-legs-4': '2 colors jeans with black right leg and grey left leg, dark grey sneakers',
  'female-legs-5': 'pale blue baggy pants with black slides',
  'female-legs-6': 'brown pants with pale aqua right sneaker and pink left sneaker',
  'female-legs-7': 'neon green baggy pants with beige right high sneaker and pink left high sneaker',
  'female-legs-8': 'green shorts with yellow right sneaker and pink left sneaker',
  'female-legs-9': 'dark purple baggy long skirt with red right sneaker and white left sneaker',
  'female-legs-10': 'neon green skirt with dark green long underpants and dark blue sneakers',
  'female-legs-11': 'neon pink shorts with half orange half blue slides',
  'female-legs-12': 'pale purple jeans with neon green sneakers',
  'female-legs-13': 'purple pants with green tall boots',
  'female-legs-14': '2 colors baggy pants, pale yellow right leg, pink left leg, pale blue slides',
  'female-legs-15': 'green and blue shorts with cyan right sneaker and purple left sneaker',
  'female-legs-16': 'baggy purple pants with neon pink sneakers',
  'female-legs-17': 'pale gold shorts with neon green undershirts and red low sneakers',
  'female-legs-18': 'green shorts with orange underpants and pale purple to grey sneakers',
  'female-legs-19': 'purple skirt, cyan underpants and bright gold sneakers',
  'female-legs-20': 'horizontal striped pants with green and dark green stripes, pale light green sneakers',
  'female-legs-avatar': 'short jean skirt with tall black boots',
};

// Helper function to get descriptive name
export function getAvatarDescription(id: string, fallbackName: string): string {
  return avatarDescriptions[id] || fallbackName;
}
